openapi: 3.0.0

info:
  title: Auth API
  description: User authentication microservice API
  version: 1.1.0

tags:
  - name: auth
    description: User authentication related operations
  - name: token
    description: Token related operations

paths:
  /api/auth/login:
    post:
      tags:
        - auth
      summary: Login a user
      description: Login a user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        "200":
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  accessToken:
                    type: string
                    format: jwt
                  refreshToken:
                    type: string
                    format: jwt
        "400":
          description: Invalid request
        "401":
          description: Unauthorized

  /api/auth/register:
    post:
      tags:
        - auth
      summary: Register a user
      description: Register a new user with email and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                username:
                  type: string
              required:
                - email
                - password
                - username
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  accessToken:
                    type: string
                    format: jwt
                  refreshToken:
                    type: string
                    format: jwt
        "400":
          description: Invalid request

  /api/auth/logout:
    post:
      tags:
        - auth
      summary: Logout a user
      description: Logout a user
      responses:
        "200":
          description: User logged out successfully

  /api/auth/validate:
    post:
      tags:
        - token
      summary: Validate a token
      description: Validate a token
      parameters:
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Token is valid
        "401":
          description: Unauthorized

  /api/auth/refresh:
    post:
      tags:
        - token
      summary: Refresh a token
      description: Refresh a token
      parameters:
        - name: Cookie
          in: header
          description: Refresh token
          required: true
          schema:
            properties:
              refreshToken:
                type: string
                format: jwt
      responses:
        "200":
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    format: jwt
        "401":
          description: Unauthorized
  
  /api/auth/data:
    get:
      tags:
        - token
      summary: Get user data
      description: Get user data
      parameters:
        - name: Authorization
          in: header
          description: Bearer token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
        "401":
          description: Unauthorized
